name: linux

on:
  push:
    paths: 
      - linux

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    
    - name: Download gcc-8
      run: sudo apt-get install gcc-8
    - name: Download linux
      run: wget https://github.com/nossoh98/linux/archive/$(git rev-parse @:./linux).zip -O linux.zip
    - name: unzip linux
      run: unzip linux.zip
    - name: build linux
      run: ./build-linux.sh linux-$(git rev-parse @:./linux) tinyconfig
